config/routes.rb
Rails.application.routes.draw do
  

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root 'pages#new'

  get '/home', to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/new', to: 'pages#new', as: "splash_page"

  get '/admin', to: 'admin#home'
  get 'admin/groups', to: 'admin#groups'
  get 'admin/shows', to: 'admin#shows'
  get 'admin/shows/new', to: 'shows#new', as: 'new_show'
  post 'admin/shows/new', to: 'shows#create'
  delete 'admin/shows/:id', to: 'shows#destroy'
  get 'admin/shows/:id/contestant', to: 'contestants#new', as: 'new_contestant'
  post 'admin/shows/:id/contestant', to: 'contestants#create'
  get 'admin/shows/:id/key', to: 'shows#key', as: 'keys'
  post 'admin/shows/:id/key', to: 'shows#keycreate'
  get 'admin/shows/:id/key/:week/edit', to: 'shows#keyedit', as: 'edit_key'
  patch 'admin/shows/:id/key/:week/', to: 'shows#keyupdate', as: 'update_key'
  put 'admin/shows/:id/key/:week/', to: 'shows#keyupdate'
  get 'admin/shows/:id/configure', to: 'shows#configure', as: 'show_weeks'
  post 'admin/shows/:id/configure', to: 'show_weeks#create'

  get '/signup', to: 'users#new', as: "signup"

  get 'contestants/index'
  get 'contestants/:id', to: 'contestants#show', as: 'contestant'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'groups/new/', to: 'groups#new', as: 'new_group'
  get 'groups/:id', to: 'groups#rankings', as: 'group_rankings'
  get 'groups/:id/picks', to: 'groups#picks', as: 'group_picks'
  get 'groups/:id/posts', to: 'groups#posts', as: 'group_posts'
  get 'groups/:id/contestants', to: 'groups#contestants', as: 'group_contestants'
  get 'groups/:id/chat', to: 'groups#chat', as: 'group_chat'

  post 'groups/:id/chat', to: 'chats#create'

  get 'groups/:id/posts/new', to: 'posts#new', as: 'new_post'
  post 'groups/:id/posts/new', to: 'posts#create'

  post 'groups/:id/posts/:post_id/comments/new', to: 'comments#create'

  get 'groups/:id/picks/week/:week', to: 'picks#new', as: 'new_picks'
  post 'groups/:id/picks/week/:week', to: 'picks#create'

  resources :users, :posts, :comments, :groups, :chats
end

app/models/group.rb
# == Schema Information
#
# Table name: groups
#
#  id         :integer          not null, primary key
#  owner_id   :integer
#  title      :string
#  show_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Group < ActiveRecord::Base
	belongs_to :owner, class_name: "User"
	has_many :members, through: :memberships, source: :user
	has_many :memberships, dependent: :destroy
	has_many :posts, dependent: :destroy
	has_many :chats, dependent: :destroy
	has_one :show, foreign_key: "id", primary_key: "show_id"
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	before_action :load_group, only: [:show, :update, :picks, :rankings, :posts, :contestants, :chat]

	def load_group
  		@group = Group.find(params[:id])
	end


	def show
	end


	def new
		@group = current_user.groups.build
		@shows = Show.all
		respond_to do |format|
			format.js
		end
	end

	def create
		# hack to force the user to be both an owner, and have a membership
		# TODO: model owner on the membership model
		custom_params = { owner_id: current_user.id }
		group_params_with_owner = group_params.merge(custom_params)
		@group = current_user.groups.create(group_params_with_owner)
		if @group.save
			flash[:success] = 'Group created.'
			redirect_to group_path(@group)
		else
		 	redirect_to '/'
		end
	end

	def update
		@group.members.push(current_user)
		redirect_to request.referrer || root_url
	end

	def destroy
		@group = Group.find(params[:id])
  	@group.destroy
  	flash[:success] = "Group deleted"
  	redirect_to request.referrer || root_url
	end

	def picks
  	@picks = @group.memberships.find_by(user: current_user).picks
	end

	def rankings
		@key = @group.show.keys
		@members = @group.memberships
	end

	def posts
		@posts = Post.where(group: @group).order(created_at: :desc)
	end

	def contestants
		@contestants = @group.show.contestants
	end

	def chat
		@new_chat = @group.chats.build
		@chats = Chat.where(group: @group).order(created_at: :desc).limit(50)
	end


	private

	def group_params
		params.require(:group).permit(:title, :show_id)
	end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_group.html.erb
<li id="group-<%= group.id %>">
	<%= link_to group.title, group, class: :"group_title" %>
	<small class="timestamp"> – Created <%= time_ago_in_words(group.created_at) %> ago.
		<% if current_user.id == group.owner_id %>
			<%= link_to "(delete)", group, method: :delete, data: { confirm: "You sure?" } %>
		<% end %>
	</small>
</li>

app/views/groups/_groupmembers.html.erb
<div class="row clearfix">
  <% @group.members.each do |member| %>
  	<div class="col-xs-3 col-md-3">
  		<%= link_to image_tag(member.image_link), member, class: :"thumbnail player-image" %>
  		<div class="caption small player-name"><%= member.first_name %></div>
  	</div>
  <% end %>
</div>

app/views/groups/_new.html.erb
<%= form_for @group do |f| %>
<div class="form-group">
	<%= f.text_area :title, placeholder: "Name that shit...", class: :"form-control" %>
</div>
<div class="form-group">
	<%= f.select (:show_id), options_from_collection_for_select(Show.all, :id, :title), {}, 
    { class: :"form-control" } %> 
</div>

	<%= f.submit "Create Group", class: :"btn btn-default" %>
<% end %>

app/views/groups/_tabs.html.erb
<div class="row">
	<div class="col-xs-12 col-sm-3 players-box">
		<h3 class="text-center">Players</h3>
		<%= render 'groupmembers' %>
	</div>
	<div class="clearfix visible-xs-block"></div>
	<div class="col-xs-12 col-sm-9">
		<h1><%= @group.title %></h1><small>You're Watching: <%= @group.show.title %></small>
		<% unless @group.members.include? current_user %>
			<%= button_to "Join Group", @group, method: :patch %>
		<% end %>
		<ul class="nav nav-tabs group-tabs">
		  <li role="presentation" class="<%= 'active' if params[:action] == 'rankings' %>" id="rankings"><%= link_to "Rankings", group_rankings_path(@group) %></li>
		  <% if @group.members.include? current_user %>
		  	<li role="presentation" class="<%= 'active' if params[:action] == 'picks' %>" id="picks"><%= link_to "My Picks", group_picks_path(@group) %></li>
		  	<li role="presentation" class="<%= 'active' if params[:action] == 'chat' %>" id="chat"><%= link_to "Chat", group_chat_path(@group) %></li>
		  	<li role="presentation" class="<%= 'active' if params[:action] == 'posts' %>" id="posts"><%= link_to "Posts", group_posts_path(@group) %></li>
		  	<li role="presentation" class="<%= 'active' if params[:action] == 'contestants' %>" id="contestants"><%= link_to "Contestants", group_contestants_path(@group) %></li>
		  <% end %>
		</ul>
		<div class="group-details col-md-12">
			<%= yield %>
		</div>
	</div>
</div>

app/views/groups/chat.html.erb
<%= render layout: 'tabs' do %>
	<%= render 'chats/new' %>
	<div class="panel panel-default" id="chats">
		<div class="panel-body">
			<ul class="media-list">
				<%= render @chats %>
			</ul>
		</div>
	</div>
<% end %>

app/views/groups/contestants.html.erb
<%= render layout: 'tabs' do %>
	<% @contestants.each do |contestant| %>
		<div class="col-xs-4 col-md-4">
			<div class="thumbnail">
				<%= link_to image_tag(contestant.image), contestant%>
				<div class="caption text-center">
					<h4><%= contestant.name %></h4>
				</div>
			</div>
		</div>
	<% end %>
<% end %>

app/views/groups/grouprankings.js.erb
$('.group-details').html("<%= escape_javascript(render :partial => 'grouprankings') %>");
$('#picks').attr('class', 'none');
$('#posts').attr('class', 'none');
$('#rankings').addClass('active');

app/views/groups/new.js.erb
$('#new-group').html("<%= escape_javascript(render :partial => 'new') %>");

app/views/groups/picks.html.erb
<%= render layout: 'tabs' do %>
	<% @group.show.show_weeks.each do |week| %>
		<div class="row">
			<div class="col-xs-12 col-md-12">
				<h4>Week <%= week.week %></h4>
			<% if @picks.where(week: week.week).any? %>
				<% @group.memberships.find_by(user: current_user).picks.where(week: week.week).each do |pick| %>
					<% @contestant = Contestant.find(pick.contestant_id) %>
					<div class="col-xs-3 col-md-3">
						<% if Key.where(show: @group.show).where(week: week.week).any? %>
							<% if Key.where(show: @group.show).where(week: week.week).where(contestant: @contestant).any? %>
								<%= link_to image_tag(@contestant.image), @contestant, class: :"thumbnail contestant-image" %>
							<% else %>
								<%= link_to image_tag(@contestant.image), @contestant, class: :"thumbnail contestant-image eliminated" %>
							<% end %>
						<% else %>
							<%= link_to image_tag(@contestant.image), @contestant, class: :"thumbnail contestant-image" %>
						<% end %>
					<div class="caption small contestant-name"><%= @contestant.name %></div>
					</div>
				<% end %>
			<% else %>
				<%= link_to "Make Picks", new_picks_path(week: week), class:"btn btn-default"  %>
			<% end %>
			</div>
		</div>
	<% end %>
<% end %>

app/views/groups/posts.html.erb
<%= render layout: 'tabs' do %>
	<%= link_to "New Post", new_post_path, class: :"btn btn-success btn-block", role: :"button", remote: :true, id: :"new-button" %>
	<div id="new-post">
		<!-- This is where the post input will appear -->
	</div>
	
	<% if @posts.any? %>
	<%= render "posts/group_posts" %>
	<% end %>
<% end %>

app/views/groups/rankings.html.erb
<%= render layout: 'tabs' do %>
	<ul class="list-group">
		<% @members.each_with_index do |member, num| %>
			<li class="list-group-item">
        <span class="badge"><%= member.score %> Points</span>
				<%= num + 1 %>. <%= User.find(member.user_id).first_name %> <% if member.made_all_picks? %>- Picks are in! Top 4: <%= member.top_four.map { |pick| pick.contestant.name } %><% end %>
			</li>
		<% end %>
	</ol>
<% end %>

app/views/groups/show.html.erb
<%= render layout: 'tabs' do %>
	<%= yield %>
<% end %>