config/routes.rb
Rails.application.routes.draw do
  

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users

  root 'pages#new'

  get '/home', to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/new', to: 'pages#new', as: "splash_page"

  get '/admin', to: 'admin#home'
  get 'admin/groups', to: 'admin#groups'
  get 'admin/shows', to: 'admin#shows'
  get 'admin/shows/new', to: 'shows#new', as: 'new_show'
  post 'admin/shows/new', to: 'shows#create'
  delete 'admin/shows/:id', to: 'shows#destroy'
  get 'admin/shows/:id/contestant', to: 'contestants#new', as: 'new_contestant'
  post 'admin/shows/:id/contestant', to: 'contestants#create'
  get 'admin/shows/:id/key', to: 'shows#key', as: 'keys'
  post 'admin/shows/:id/key', to: 'shows#keycreate'
  get 'admin/shows/:id/key/:week/edit', to: 'shows#keyedit', as: 'edit_key'
  patch 'admin/shows/:id/key/:week/', to: 'shows#keyupdate', as: 'update_key'
  put 'admin/shows/:id/key/:week/', to: 'shows#keyupdate'
  get 'admin/shows/:id/configure', to: 'shows#configure', as: 'show_weeks'
  post 'admin/shows/:id/configure', to: 'show_weeks#create'

  get '/signup', to: 'users#new', as: "signup"

  get 'contestants/index'
  get 'contestants/:id', to: 'contestants#show', as: 'contestant'

  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get 'groups/new/', to: 'groups#new', as: 'new_group'
  get 'groups/:id', to: 'groups#rankings', as: 'group_rankings'
  get 'groups/:id/picks', to: 'groups#picks', as: 'group_picks'
  get 'groups/:id/posts', to: 'groups#posts', as: 'group_posts'
  get 'groups/:id/contestants', to: 'groups#contestants', as: 'group_contestants'
  get 'groups/:id/chat', to: 'groups#chat', as: 'group_chat'

  post 'groups/:id/chat', to: 'chats#create'

  get 'groups/:id/posts/new', to: 'posts#new', as: 'new_post'
  post 'groups/:id/posts/new', to: 'posts#create'

  post 'groups/:id/posts/:post_id/comments/new', to: 'comments#create'

  get 'groups/:id/picks/week/:week', to: 'picks#new', as: 'new_picks'
  post 'groups/:id/picks/week/:week', to: 'picks#create'

  resources :users, :posts, :comments, :groups, :chats
end

app/models/show.rb
# == Schema Information
#
# Table name: shows
#
#  id         :integer          not null, primary key
#  title      :string
#  start      :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Show < ActiveRecord::Base
	has_many :contestants
	has_many :show_weeks, dependent: :destroy
	has_many :keys
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
	layout "admin", only: [:new, :key, :keyedit, :configure]

	def new
		@show = Show.new
	end

	def create
		@show = Show.new(show_params)
		if @show.save 
    		redirect_to show_weeks_path(@show)
  		else 
    		redirect_to admin_shows_path
  		end 
	end

	def key
		@show = Show.find(params[:id])
		@new_key = @show.keys.build
	end

	def keycreate #VERY BADLY NEEDS REFACTORING
		@show = Show.find(params[:id])
		@new_key = @show.keys.build
		week = 
		
		params["key"]["contestant_id"][0..-2].each do |contestant_id|
			@new_key = @show.keys.create(contestant_id: contestant_id, week: params["key"]["week"])
		end
		
		keys = Key.where(show: @show).where(week: params["key"]["week"])
		winners = []
		
		keys.each do |key|
			winner = Contestant.find(key.contestant_id)
			winners.push(winner)
		end
		
		players = Membership.where(group: Group.where(show_id: @show.id))
		players.each do |player|
			player_picks = player.picks.where(week: params["key"]["week"])
			player_winners = []
			
			player_picks.each do |player_pick|
				player_winner = Contestant.find(player_pick.contestant_id)
				player_winners.push(player_winner)
			end
			
			matches = winners & player_winners

			#TODO - LET ADMIN CONFIGURE SCORING STRUCTURE
			if params["key"]["week"].to_i == 1
				player.score = player.score + (matches.count * 2)
			elsif params["key"]["week"].to_i == 2
				player.score = player.score + (matches.count * 3)
			elsif params["key"]["week"].to_i == 3
				player.score = player.score + (matches.count * 4)
			elsif params["key"]["week"].to_i == 4
				player.score = player.score + (matches.count * 5)
			elsif params["key"]["week"].to_i == 5
				player.score = player.score + (matches.count * 6)
			elsif params["key"]["week"].to_i == 6
				player.score = player.score + (matches.count * 10)
			elsif params["key"]["week"].to_i == 7
				player.score = player.score + (matches.count * 15)
			elsif params["key"]["week"].to_i == 8
				player.score = player.score + (matches.count * 20)
			elsif params["key"]["week"].to_i >= 9
				player.score += (matches.count * 30)
			end		

			player.save
		end
		
		redirect_to show_weeks_path(@show)
	end

	def keyedit
		@key = Key.where(show: params[:id]).where(week: params[:week])
	end

	def keyupdate
		@key = Key.where(show: params[:id]).where(week: params[:week])
		params["key"]["contestant_id"][0..-2].each do |contestant_id|
			@key = @show.keys.update_attributes(contestant_id: contestant_id, week: params["key"]["week"])
		end
  		if @key.save
  			redirect_to show_week_path(@show)
  		else
  			redirect_to show_week_path(@show)
  		end
	end

	def configure
		@show = Show.find(params[:id])
		@show_week = @show.show_weeks.build
	end

	def destroy
		@show = Show.find_by(id: params[:id])
    	@show.delete
    	redirect_to admin_shows_path
  	end


	private

	def show_params
		params.require(:show).permit(:title, :start)
	end

	def key_params
		params.permit(:contestant_id, :week)
	end
	

end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/views/shows/configure.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <h1 class="page-header"><%= @show.title %> - Settings</h1>
  <div class="row sub-header">
	  <% if @show.show_weeks.count == 0 %>
	  	<%= form_for @show_week, url: :show_weeks do |f| %>
	  	<div class="form-group">
			<%= f.label :"How many picks in Week 1?" %>
			<%= f.text_field :picklimit %>
		</div>
			<%= f.hidden_field :week, value: 1 %>
			<%= f.submit "Submit", class: :"btn btn-default" %>
		<% end %>
	  <% else %>
	  	<div class="col-sm-12 col-md-5">
			<%= form_for @show_week, url: :show_weeks do |f| %>
		  	<div class="form-group">
		  		<% week = (@show.show_weeks.count + 1) %>
				<%= f.label :"How many picks in Week #{week}?" %>
				<%= f.text_field :picklimit %>
			</div>
				<%= f.hidden_field :week, value: week %>
				<%= f.submit "Submit", class: :"btn btn-default" %>
			<% end %>
		</div>
		<div class="col-sm-12 col-md-4">
			<div class="table-responsive">
    			<table class="table table-striped">
    				<thead>
				        <tr>
				          <th class="text-center">Week</th>
				          <th class="text-center"># Of Picks</th>
				          <th class="text-center">Key</th>
				        </tr>
				    </thead>
				    <tbody>
					  	<% @show.show_weeks[0...-1].each do |show_week| %>
					  		<tr>
					  			<td class="text-center"><%= show_week.week %></td>
					  			<td class="text-center"><%= show_week.picklimit %></td>
					  			<% if @show.keys.where(week: show_week.week).any? %>
					  				<td class="text-center"><%= link_to "Edit Key", edit_key_path(week: show_week.week) %></td>
					  			<% elsif show_week.week == 1 || @show.keys.where(week: (show_week.week-1)).any? %>
					  				<td class="text-center"><%= link_to "Create Key", keys_path(week: show_week.week) %></td>
				  				<% else %>
				  					<td class="text-center"> </td>
				  				<% end %>
					  		</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	  <% end %>
	</div>
	<div class="row sub-header">
		<h1>Contestants <%= link_to "Add Contestant", new_contestant_path, class: "btn btn-success" %></h1> 
		<% @show.contestants.order(:name).each do |contestant| %>
		<div class="col-xs-4 col-md-2">
			<div class="thumbnail">
				<%= link_to image_tag(contestant.image), contestant%>
				<div class="caption text-center">
					<h4><%= contestant.name %></h4>
				</div>
			</div>
		</div>
		<% end %>
	</div>

</div>

app/views/shows/key.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <h1 class="page-header">Key For <%= @show.title %></h1>
	<% unless @show.keys.where(week: 1).any? %>
		<h1> Make week 1 key </h1>
		<%= form_for @new_key, url: keys_path, method: "post" do |f| %>
		<% contestants = Contestant.where(show: @show).order(:name) %>
		<div class="row">
			<%= f.collection_check_boxes :contestant_id, contestants, :id, :name do |b| %>
				<div class="col-md-2">
					<%= b.check_box %><br />
					<%= b.label %>
				</div>
			<% end %>
		</div>
		<%= f.hidden_field :week, value: 1 %>
		<div class="row" id="limit_checkbox">
			<%= f.submit "Submit", class: :"btn btn-default", id: :"submit-button" %>
		</div>
		<% end %>		
	<% else %>
		<h1> Make week <%= params[:week] %> key </h1>
		<%= form_for @new_key, url: keys_path, method: "post" do |f| %>
		<% last_week_keys = Key.where(show: @show).where(week: (params["week"].to_i - 1)) %>
		<% contestants = [] %>
		<% last_week_keys.each do |key| %>
			<% contestants.push(key.contestant) %>
		<% end %>
		<div class="row">
			<%= f.collection_check_boxes :contestant_id, contestants, :id, :name do |b| %>
				<div class="col-md-2">
					<%= b.check_box %><br />
					<%= b.label %>
				</div>
			<% end %>
		</div>
		<%= f.hidden_field :week, value: params[:week] %>
		<div class="row" id="limit_checkbox">
			<%= f.submit "Submit", class: :"btn btn-default", id: :"submit-button" %>
		</div>
		<% end %>
	<% end %>
  
</div>
    

app/views/shows/keyedit.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
	<h1> Make week <%= params[:week] %> key </h1>
	<%= form_for @key, url: edit_key_path, method: "patch" do |f| %> <!--Something Wrong! -->
	<% contestants = Contestant.where(show: @show).order(:name) %>
	<div class="row">
		<%= f.collection_check_boxes :contestant_id, contestants, :id, :name do |b| %>
			<div class="col-md-2">
				<%= b.check_box %><br />
				<%= b.label %>
			</div>
		<% end %>
	</div>
	<%= f.hidden_field :week, value: params[:week] %>
	<div class="row" id="limit_checkbox">
		<%= f.submit "Update", class: :"btn btn-default" %>
	</div>
	<% end %>
</div>

app/views/shows/new.html.erb
<div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
  <h1 class="page-header">New Show</h1>
  <%= form_for @show, url: :new_show do |f| %>
    <div class="form-group">
      <%= f.label :Title %>
      <%= f.text_field :title, class: :"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :Starts %>
      <%= f.datetime_select :start, class: :"form-control" %>
    </div>

      <%= f.submit "Create", class: :"btn btn-default" %>
  <% end %>
</div>
    